- package.json
- src/browser.js
It seems my last few changes adding development modes broke the release build, because I assumed `NODE_ENV` would always be `production` in a release build but apparently that's not the case.
See related discussion here: https://github.com/electron-userland/electron-builder/issues/1966
I don't really want to pull in [`electron-is-dev`](https://github.com/sindresorhus/electron-is-dev) just for this, so I'm doing the simple manual fix.
> Default to production build, unless told otherwise

- src/browser.js
[From spec:](https://docs.google.com/document/d/1qYETgpZuYiubKVsRprgGzlj6kEb9W7Xc1Gt6as8v3sA/edit#bookmark=id.aqfov2eb59dc)
> Home button should take use to sign in page if they aren’t signed in and studio.code.org/home if they are signed in
While not a "perfect" check for whether we are signed in, we're [depending on the user short name cookie](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/initSigninState.js) to check sign-in state in our main application and this seems to be highly reliable (Brent just looked into this quite a bit).  I've done the same thing here, depending on getting the cookie name from the host page since it can change depending on whether we're in a dev, test or prod environment.
Right now we're only changing the Home button behavior …
> Vary home button behavior based on sign-in state

- src/browser.js
- src/main.js
- src/menus.js
Adds simple custom menus to the browser (where previously we had none at all).  I'm mostly doing this for our own uses, providing these two features:
* We can quickly check which version of the browser we're looking at in the help menu.
* We can toggle developer tools (for either the electron layer or the webview layer) at will in our release builds.
The latter I especially need to track down a Maker connection bug that won't repro with development builds but does repro with release builds coming out of Travis.
References: [This documentation](https://electron.atom.io/docs/api/menu/) and [this tutorial](https://www.christianengvall.se/electron-menu/).
> Add custom menus

- src/User.js
- src/browser.js
The `userNameCookieKey` was removed from our main project by Brent today in [this pull request](https://github.com/code-dot-org/code-dot-org/pull/18814).  Instead, the client has access to the current `rack_env` and has to adjust its own cookie keys accordingly.
Once I had that working, I encapsulated much of this logic into a helper class.  It's probably time to start organizing this code! :grin:
> Update how we check sign-in state

- .eslintrc.js
- package.json
- src/User.js
- src/browser.js
- src/defaults.js
- src/main.js
- src/menus.js
- src/originWhitelist.js
- src/preload.js
- test/.eslintrc.js
- test/originWhitelistTest.js
- yarn.lock
Adds mocha and eslint to the project.
Adds some new yarn commands:
- `yarn lint` will run the linter, and also autofix anything it can.
- `yarn test` will run the linter _without_ autofix, and then run unit tests.
Linting and tests now run as part of CI before the release build.
Most changes in this PR are from the linter autofixing existing code. :grin:
> Lint and test

- package.json
- src/originWhitelist.js
- src/preload.js
- src/wrapNavigation.js
- test/originWhitelistTest.js
More whitelisting to support OAuth.  I haven't manually tested this one, because apparently only one developer account has access to our test OAuth integration here.
New/changed tests:
```
openUrlInDefaultBrowser
✓ true for https://accounts.google.com.example.org
✓ true for https://example.org/?returnTo=accounts.google.com
✓ true for https://live.com
✓ true for https://live.com.example.org
✓ true for https://example.org/?returnTo=live.com
✓ false for https://login.live.com/oauth20_authorize.srf
✓ false for http://login.live.com/logout.srf
mayInjectNativeApi
✓ blocks https://login.live.com
✓ blocks http://login.live.com
✓ blocks https://accounts.google.com.example.org
✓ blocks https://example.org
✓ blocks https://live.com
✓ blocks https://live.com.example.org
```
> Microsoft OAuth support

- src/originWhitelist.js
- src/preload.js
- src/wrapNavigation.js
- test/originWhitelistTest.js
Whitelists `accounts.google.com` to load within the Maker Toolkit Browser, which lets students sign in to Code.org with Google OAuth entirely within the app.
That change was small - the rest of the diff is rearranging the whitelist logic to have slightly different whitelists for what loads within the app, and which pages get the native APIs we need for Maker functionality.  In short: Only pages at Code.org-owned origins get the native APIs, while the whitelist of pages to load in the app is slightly broader than that.
> Google OAuth support

- package.json
- src/originWhitelist.js
- src/preload.js
- src/wrapNavigation.js
- test/originWhitelistTest.js
Whitelists OAuth login/logout URLs, while blacklisting facebook.com generally, so that we can support Facebook login to Code.org but otherwise open Facebook in the default browser.
New/changed tests:
```
openUrlInDefaultBrowser
✓ true for https://www.google.com
✓ true for https://www.facebook.com
✓ false for https://accounts.google.com
✓ false for https://accounts.google.com/signin/oauth
✓ false for https://accounts.google.com/logout
✓ false for https://www.facebook.com/v2.6/dialog/oauth
✓ false for https://www.facebook.com/logout.php
✓ false for https://www.facebook.com/logout.php?next=https://code.org/&access_token=XXXXXX|YYYYYYYYYYYY|ZZZZZZ
mayInjectNativeApi
✓ blocks https://accounts.google.com
✓ blocks https://www.facebook.com
✓ blocks https://www.google.com
```
> Facebook OAuth support

- package.json
At least on my machine, I have to add specific targets to build Linux and Mac locally (on OS X)
> Add Windows and Linux build targets

- src/browser.js
- src/defaults.js
- src/index.html
- src/originWhitelist.js
- test/originWhitelistTest.js
Adds a Clever.com login button to the Maker Browser toolbar and whitelists Clever login flow URLs, so that it's possible to sign in to Code.org via Clever within the Maker Browser.
Design-wise this is a little clumsy right now, but getting it functional is the first priority.
Clicking the button takes the student to the District login page, if they've signed in using Maker Browser before...
Or this generic login page if they have not (which includes a working Clever Badge login option):
Once signed in to Clever students will see their apps on Clever's site within Maker Browser:
And can click on Code.org to get signed in:
> Clever Login Button

- .travis.yml
Use yarn's `--frozen-lockfile` flag when running `yarn install` in CI, so that the build fails if `yarn install` would generate any changes to the lockfile.
> CI yarn with --frozen-lockfile

- config/_release.json
- package.json
Also disables Github releases, because something goes wrong when uploading all the artifacts in parallel. Looking into reenabling that in a separate PR.
> Enable 32 bit builds

- src/menus.js
Based on https://pracucci.com/atom-electron-enable-copy-and-paste.html - seems to Just Work(tm) on OS X:
> Add edit menu, enable copy/paste

- src/browser.css
While testing the addition of cut/copy/paste/select-all hotkeys, I noticed that it's possible to select the buttons in the browser toolbar.  We probably don't want to allow that, so I'm disabling it.
> Toolbar shouldn't be selectable

- config/_release.json
- package.json
This enforces code signing when trying to publish a build, to avoid mistakes like I made yesterday when I forgot to set my environment variables to pull in the signing keys.
This should not affect local builds, as the forceCodeSigning key is only pulled in when using the release config.
Also bumps version to 1.0.4
> Enforce code signing when publishing

- src/openUrlModal/index.js
- src/openUrlModal/view.css
- src/openUrlModal/view.html
- src/openUrlModal/view.js
Two changes to mitigate problems with this dialog on OSX (before image):
- Adds a "Cancel" button - apparently on OSX there isn't a close button on the window by default.
- Makes the modal a little taller.
New appearance on Ubuntu/Gnome:
I'd appreciate verification on OSX since I don't have access to it.
([Axosoft item 1269: Fix UI for entering arbitrary URL UI](https://codeorg.axosoft.com/viewitem?id=1269&type=features&force_use_number=true))
> Improve the "Open URL" modal

- src/defaults.js
Turns out this was super-easy to do, but I don't want to ship this until at least https://github.com/code-dot-org/code-dot-org/pull/20804 ships, and maybe a couple follow-up items I have close on its heels.
Note, this changes the default page loaded on launch, and where we navigate when you click the HOME button.  In both cases if you are not signed in, you'll be redirected to the sign-in page, which will redirect you back to /maker/home after auth.
> HOME is now the new maker homepage

- src/originWhitelist.js
- test/originWhitelistTest.js
Requested independently in two Zendesk tickets:
- https://codeorg.zendesk.com/agent/tickets/135552
- https://codeorg.zendesk.com/agent/tickets/134994
It would be preferable not to handle school-specific URLs here but we don't currently have a good workaround.
I'm not entirely sure this will solve the problem for this district, as I don't have details on their OAuth flow beyond the origin they supplied.  Rather than asking them to track the whole series of redirects involved from their end, I think we should release this quick fix and ask them to test it.  In the meantime we should set up metrics on whitelist misses that will make this easier to diagnose/fix from our end in the future.
> Whitelist sso.pcsd1.org

- src/originWhitelist.js
- test/originWhitelistTest.js
Follow-up to https://github.com/code-dot-org/browser/pull/33 still trying to unblock PCSD1. We got a [response in Zendesk](https://codeorg.zendesk.com/agent/tickets/135552) today saying:
> We do get one step further along. We are able to hit our SSO portal page within the Toolkit browser now. Once we hit “sign in” we are booted out and appear to land on accounts.google.com which I know is in your whitelist already. I did a little digging and I think there is an intermediate redirect that is kicking us out:
> 
> https://www.google.com/a/pcsd1.org/acs
That would definitely do it.   I might be whitelisting all of GSuite here (`https://www.google.com/a/` redirects to `https://gsuite.google.com/`) or maybe just the GSuite admin pages, but that seems like a reasonable starting point - the …
> Whitelist GSuite URL

- package.json
- src/checkForManualUpdate.js
- src/main.js
Detects if the user is running 1.0.9, and if so, prompts them to manually download a new version.
The deployment plan is that we'll publish this as 1.0.9, and then immediately publish 1.1.0 with the branding update in https://github.com/code-dot-org/browser/pull/31 (which users will not be able to auto-update to).
Note that this also disables the auto-update check on 1.0.9, because based on testing, once the newer version is pushed with a different package name, every auto-update check will download the whole update and then fail to install it.
> Add manual update popup

- config/_release.json
To match rebranding, we change the download location from makertoolkit -> maker.
This is related to #31, so we could make sure that the 1.0.x line doesn't try to update into the 1.1.x line (which will fail because of the package name change).
> Move S3 directory for 1.1.x releases

- config/_common.json
- package.json
Flips the switch on one-click install to "false" on Windows to enable per-machine installation.
> Enable multi-user install on Windows, bump to 1.1.2

- src/originWhitelist.js
- test/originWhitelistTest.js
We got a report of an OAuth redirect sequence that goes through `www.google.com/accounts/signin/continue` (instead of `accounts.google.com/signin/oauth` like the paths we've observed so far).  Expanding the whitelist to include that path.
> Whitelist google.com/accounts for redirects

- package.json
- src/firehose.js
- src/main.js
- src/menus.js
- src/utils.js
- src/wrapNavigation.js
- yarn.lock
Bringing over a slightly modified version of the Javascript Firehose logging utility from the main Code.org repo (https://github.com/code-dot-org/code-dot-org/blob/cf42f5b69ae8199e6fb254a207b9d04e3ffacd37/apps/src/lib/util/firehose.js).
Also added logging for two events that we're interested in:
1) Auto-update errors (study: maker-autoupdate, event: error)
2) URL whitelisting failures (study: maker-whitelist, event: url-not-in-whitelist)
These will show up in dashboard.analysis.events in Redshift, like when we log from CDO.
> Add Firehose logging for metrics reporting

- src/originWhitelist.js
- src/wrapNavigation.js
To get away from having to support an ever-growing list of per-school whitelisted domains for oauth, we just skip the whitelist check altogether during the oauth process.
> Disable whitelist check during oauth flow

- .gitignore
When building via Docker, it can be useful to have Windows code signing files in the project directory, so we should ignore them in git.
> Ignore all .p12 files in project

- package.json
- src/firehose.js
- src/openUrlModal/index.js
- yarn.lock
Logging events were not properly getting through to Redshift, and after some investigation it turned out that this was because NODE_ENV is not set when running a built version of the app (nor should it be). The right way to check environment is to use the `electron-is-dev` library.
In the meantime, I also noticed that I had missed instrumenting one of the whitelist checks, so am updating that as well.
This PR also switches a few logging statements from using `console.log` to the proper electron logger, which reliably logs in any environment.
> Fix whitelist logging

- README.md
- src/openUrlModal/index.js
- src/openUrlModal/view.js
- src/originAllowlist.js
- src/preload.js
- src/wrapNavigation.js
- test/originAllowlistTest.js
([STAR-186](https://codedotorg.atlassian.net/browse/STAR-186)) We've had a spike of helpdesk tickets from teachers having trouble with SSO in the Code.org Maker App, specifically caused by this feature that kicks the user to their default browser when navigating to a URL not on our allow-list.  Per [this Slack discussion](https://codedotorg.slack.com/archives/C0T0EGE8L/p1552949091009600) we don't treat this as a selling point for the app, and are okay with removing this "security" feature to solve the widespread sign-in issues.
Note, we still use the allowlist to decide when to inject our custom Maker API (which includes node-serialport) into the page, so that we're not allowing arbitrary pages visited through the Maker App to interact with the user's serialport.
With these changes I've …
> Never kick navigation to default browser

- package.json
- src/preload.js
- yarn.lock
Surfaces the 'flashBoardFirmware' to the window of the Maker Browser so that we can access it from the website.
FlashBoardFirmware accepts a board type as a parameter and if that board type matches to the CP Classic, we flash the firmware from a hard-coded url to the board.
Next steps:
Establish protocol for what hex file to pull from.
Connect to the maker setup checklist: https://github.com/code-dot-org/code-dot-org/pull/30227/files
> Flash Firmware to Circuit Playground Classics

- src/browser.js
- src/defaults.js
- src/index.html
Part of solving the Google OAuth issue in Maker Toolkit.
Adds button to maker. Opens page in default browser. Opens page in maker browser.
Spec: https://docs.google.com/document/d/1Vd8btlBuTN90Qu57EYpKxb90z7ApuAd6oC2z0JDAKYg/edit
> Add Google OAuth Button

- package.json
- yarn.lock
Reports on Zendesk that classes on Linux in the Maker app were seeing this error:
Traced it back to not being able to load the preload file because node was throwing an error that the serialport was using ES6, but they were using a version of Node that didn't support that. Discovered that the version of Electron we were using was on Node v.8.2.1. Updated the version of Electron from 1.8.8 to 2.0.0 (most recent is 8.x.x.) and this used a more recent version of node that support ES6.
For those not on Linux, please pull and test that you can run a project with the board!
> Update Electron to version that support ES6

- package.json
- src/preload.js
- yarn.lock
Context: We need to update electron-packager in order to get our continuous integration tests running, but we need to update to a 10.x.x version of Node to do so. This causes an error due to a library that avrgirl uses. Since we aren't currently using the avrgirl code, and it's not on our short term plan, I pulled out the code in the code-dot-org repository and here so we can unblock the other updates we need here.
Documentation on what was removed: https://docs.google.com/document/d/1jJYT-dZyPHdCSj1dl03EMCFq2qcduFS9FHJ-kfkSZT8/edit
PR of this change on the code-dot-org side: https://github.com/code-dot-org/code-dot-org/pull/38542
PR where we added this: https://github.com/code-dot-org/browser/pull/52/files
> Remove AvrGirl

- .travis.yml
- README.md
- package.json
- yarn.lock
Updating electron libraries to get us to a green run. To do this, we needed to update to node 10, which required us to pull out the Avrgirl library, see https://github.com/code-dot-org/browser/pull/79.
> Update libraries after Avrgirl Removed

- package.json
- src/main.js
- yarn.lock
Adding a context menu to make copy and pasting easier for students. Gif below shows added behavior.
Uses electron-context-menu library. Needed to update Electron to use the library.
> Add context menu for copy and paste

- src/browser.js
- src/defaults.js
NOTE: this should not be merged until the [related PR in Code Studio](https://github.com/code-dot-org/code-dot-org/pull/38245) is deployed.
A few changes here:
1. When a user was already logged in, they were seeing an error instead of the "magic code" to paste into Maker App. This takes them directly to the code page if they're already logged in. 
2. If a user tries to log in without a google authentication option, show them a more useful message (final wording still in progress). This is actually handled in the [related PR](https://github.com/code-dot-org/code-dot-org/pull/38245) in Code Studio
Here's a video for when a user is not logged in and uses a valid google auth option: https://drive.google.com/file/d/1_fvrYv2oMNnOcluvxi2LFgRiSGbIGlJW/view?usp=sharing 
Here's a video for when a …
> change sign in url to go directly to the confirm login page

- README.md
- src/browser.js
- src/main.js
Video of process: 
We want to find an unobtrusive way to encourage folks to update their Maker App. The notification opens the maker setup page, which includes instructions to download the most recent version.
These changes also include instructions in the releasing instructions on how to add this notification for future releases. At the moment, everyone at 1.1.8 (current version) and below will see this.
> Download Version Notification

- package.json
- yarn.lock
Reverts code-dot-org/browser#87
Somehow this was affecting the ability to put values on the "window" global variable. Reverting now to continue investigation.
> Revert "Bump electron from 8.5.2 to 9.4.0"

- README.md
- src/main.js
Reverts code-dot-org/browser#86
Sometimes I get confused with how the Maker App gets updated and this was one of those situations. I realized that in order to update the suggested version, we'd need to deploy the app again, so it wouldn't tell current users to update. This should be re-implemented so that it checks somewhere online (GitHub? S3?) to see if there is a new message and then to display it. This would allow us to recommend updates or warn of potential future deprecation. But I know we are releasing the Maker App this week, so we'll need to do the work to reimplement this another time.
cc: @aaronwaggener - just a heads up we'll want this merged before deploying the Maker App.
> Revert "Download Version Notification"

- .github/workflows/main.yml
While working on adding Actions to another repo, I learned a more efficient way to have this workflow run on pull requests and `main`. 
This change causes our workflow to run for `pull_request`s (which will include any incremental pushes to the branch after a PR has been opened) and then once on `main` when we merge. Without this change we were seeing checks run twice on PRs because both the `pull_request` and `push` events were getting triggered  (see below)
**Before**
**After**
> Change GitHub Actions to only run once on pull requests

- README.md
I forgot to update our Build Status badge when I renamed the Actions workflow in https://github.com/code-dot-org/browser/pull/101.
BEFORE
[![Build Status](https://github.com/code-dot-org/browser/actions/workflows/main.yml/badge.svg?branch=main)](https://github.com/code-dot-org/browser/actions/workflows/main.yml)
AFTER
[![Build Status](https://github.com/code-dot-org/browser/actions/workflows/ci.yml/badge.svg?branch=main)](https://github.com/code-dot-org/browser/actions/workflows/ci.yml)
> Update the Build Status badge

- package.json
- yarn.lock
Reverts code-dot-org/browser#102
Broke build.
> Revert "Bump electron from 10.4.6 to 11.5.0"

- package.json
- yarn.lock
We added `electron-forge` [here](https://github.com/code-dot-org/browser/commit/08eccb89da37ea163b38c2c43731cd805a692e3d) but it doesn't appear we ever actually integrated it into our app. The package [appears to be abandoned](https://www.npmjs.com/package/electron-forge) now and as such has many outdated dependencies. Note that removing this one package reduces the size of `yarn.lock` by almost half. 
Once this is merged we can try updating additional dependencies.
Note: tested by building on Mac and a Windows VM
> Remove electron forge

- package.json
- test/originAllowlistTest.js
- yarn.lock
Refactored the one place we were using `lodash`.
> Remove lodash as a top-level dependency
